add_executable(problem-201 problem-201.c)
add_executable(problem-202 problem-202.c)
add_executable(problem-203 problem-203.c)
add_executable(problem-204 problem-204.c)
add_executable(problem-205 problem-205.c)
add_executable(problem-206 problem-206.c)
add_executable(problem-207 problem-207.c)
add_executable(problem-208 problem-208.c)
add_executable(problem-209 problem-209.c)
add_executable(problem-217 problem-217.c)
add_executable(problem-220 problem-220.c)
add_executable(problem-221 problem-221.c)
add_executable(problem-211 problem-211.c)
add_executable(problem-213 problem-213.c)
add_executable(problem-214 problem-214.c)
add_executable(problem-215 problem-215.c)
add_executable(problem-216 problem-216.c)
add_executable(problem-218 problem-218.c)
add_executable(problem-219 problem-219.c)
add_executable(problem-225 problem-225.c)
add_executable(problem-222 problem-222.c)
add_executable(problem-226 problem-226.c)
add_executable(problem-227 problem-227.c)
add_executable(problem-229 problem-229.c)
add_executable(problem-230 problem-230.c)
add_executable(problem-228 problem-228.c)

add_executable(problem-235 problem-235.c)
add_executable(problem-237 problem-237.c)
add_executable(problem-231 problem-231.c)
add_executable(problem-243 problem-243.c)
add_executable(problem-244 problem-244.c)
add_executable(problem-239 problem-239.c)
add_executable(problem-240 problem-240.c)
add_executable(problem-247 problem-247.c)
add_executable(problem-248 problem-248.c)

add_executable(problem-249 problem-249.c)
add_executable(problem-250 problem-250.c)
add_executable(problem-242 problem-242.c)

add_executable(problem-234 problem-234.c)

add_executable(problem-232 problem-232.c)

if(MATH_LIBRARY)
	target_link_libraries(problem-211 ${MATH_LIBRARY})
	target_link_libraries(problem-222 ${MATH_LIBRARY})
	target_link_libraries(problem-226 ${MATH_LIBRARY})
	target_link_libraries(problem-247 ${MATH_LIBRARY})
endif()
