add_executable(problem-051 problem-051.c)
add_executable(problem-052 problem-052.c)
add_executable(problem-053 problem-053.c)
add_executable(problem-054 problem-054.c)
add_executable(problem-055 problem-055.c)
add_executable(problem-056 problem-056.c)
add_executable(problem-057 problem-057.c)
add_executable(problem-058 problem-058.c)
add_executable(problem-059 problem-059.c)
add_executable(problem-060 problem-060.c)
add_executable(problem-061 problem-061.c)
add_executable(problem-062 problem-062.c)
add_executable(problem-063 problem-063.c)
if(MATH_LIBRARY)
  add_executable(problem-064 problem-064.c)
  target_link_libraries(problem-064 ${MATH_LIBRARY})
endif()
add_executable(problem-065 problem-065.c)
if(MATH_LIBRARY)
  add_executable(problem-066 problem-066.c)
  target_link_libraries(problem-066 ${MATH_LIBRARY})
endif()
add_executable(problem-067 problem-067.c)
add_executable(problem-068 problem-068.c)
if(MATH_LIBRARY)
  add_executable(problem-069 problem-069.c)
  target_link_libraries(problem-069 ${MATH_LIBRARY})
endif()
add_executable(problem-070 problem-070.c)
add_executable(problem-071 problem-071.c)
add_executable(problem-072 problem-072.c)
add_executable(problem-073 problem-073.c)
add_executable(problem-074 problem-074.c)
add_executable(problem-075 problem-075.c)
add_executable(problem-076 problem-076.c)
add_executable(problem-077 problem-077.c)
add_executable(problem-078 problem-078.c)
add_executable(problem-079 problem-079.c)
if(MATH_LIBRARY)
  add_executable(problem-080 problem-080.c)
  target_link_libraries(problem-080 ${MATH_LIBRARY})
endif()
add_executable(problem-081 problem-081.c)
add_executable(problem-082 problem-082.c)
add_executable(problem-083 problem-083.c)
add_executable(problem-084 problem-084.c)
add_executable(problem-085 problem-085.c)
if(MATH_LIBRARY)
  add_executable(problem-086 problem-086.c)
  target_link_libraries(problem-086 ${MATH_LIBRARY})
endif()
add_executable(problem-087 problem-087.c)
add_executable(problem-088 problem-088.c)
add_executable(problem-089 problem-089.c)
add_executable(problem-090 problem-090.c)
add_executable(problem-091 problem-091.c)
add_executable(problem-092 problem-092.c)
if(MATH_LIBRARY)
  add_executable(problem-093 problem-093.c)
  target_link_libraries(problem-093 ${MATH_LIBRARY})
endif()
add_executable(problem-094 problem-094.c)
add_executable(problem-095 problem-095.c)
add_executable(problem-096 problem-096.c)
add_executable(problem-097 problem-097.c)
if(MATH_LIBRARY)
  add_executable(problem-098 problem-098.c)
  target_link_libraries(problem-098 ${MATH_LIBRARY})
  add_executable(problem-099 problem-099.c)
  target_link_libraries(problem-099 ${MATH_LIBRARY})
endif()
add_executable(problem-100 problem-100.c)
