add_executable(problem-151 problem-151.c)
add_executable(problem-152 problem-152.c)
add_executable(problem-153 problem-153.c)
add_executable(problem-154 problem-154.c)
add_executable(problem-155 problem-155.c)
add_executable(problem-156 problem-156.c)
add_executable(problem-157 problem-157.c)
add_executable(problem-158 problem-158.c)
add_executable(problem-159 problem-159.c)
add_executable(problem-160 problem-160.c)
add_executable(problem-161 problem-161.c)
add_executable(problem-162 problem-162.c)
add_executable(problem-163 problem-163.c)
add_executable(problem-164 problem-164.c)
add_executable(problem-165 problem-165.c)
add_executable(problem-166 problem-166.c)
add_executable(problem-167 problem-167.c)
add_executable(problem-168 problem-168.c)
add_executable(problem-169 problem-169.c)
add_executable(problem-170 problem-170.c)
add_executable(problem-171 problem-171.c)
add_executable(problem-172 problem-172.c)
add_executable(problem-173 problem-173.c)
add_executable(problem-174 problem-174.c)
add_executable(problem-175 problem-175.c)
add_executable(problem-176 problem-176.c)
add_executable(problem-177 problem-177.c)
add_executable(problem-178 problem-178.c)
add_executable(problem-179 problem-179.c)
add_executable(problem-180 problem-180.c)
add_executable(problem-181 problem-181.c)
add_executable(problem-182 problem-182.c)
add_executable(problem-183 problem-183.c)
add_executable(problem-184 problem-184.c)
add_executable(problem-185 problem-185.c)
add_executable(problem-186 problem-186.c)
add_executable(problem-187 problem-187.c)
add_executable(problem-188 problem-188.c)
add_executable(problem-189 problem-189.c)
add_executable(problem-190 problem-190.c)
add_executable(problem-191 problem-191.c)
add_executable(problem-192 problem-192.c)
add_executable(problem-193 problem-193.c)
add_executable(problem-194 problem-194.c)
add_executable(problem-195 problem-195.c)
add_executable(problem-196 problem-196.c)
add_executable(problem-197 problem-197.c)
add_executable(problem-198 problem-198.c)
add_executable(problem-199 problem-199.c)
add_executable(problem-200 problem-200.c)

if(MATH_LIBRARY)
	target_link_libraries(problem-183 ${MATH_LIBRARY})
	target_link_libraries(problem-177 ${MATH_LIBRARY})
	target_link_libraries(problem-153 ${MATH_LIBRARY})
	target_link_libraries(problem-180 ${MATH_LIBRARY})
	target_link_libraries(problem-184 ${MATH_LIBRARY})
	target_link_libraries(problem-190 ${MATH_LIBRARY})
	target_link_libraries(problem-192 ${MATH_LIBRARY})
	target_link_libraries(problem-193 ${MATH_LIBRARY})
	target_link_libraries(problem-195 ${MATH_LIBRARY})
	target_link_libraries(problem-196 ${MATH_LIBRARY})
	target_link_libraries(problem-197 ${MATH_LIBRARY})
	target_link_libraries(problem-199 ${MATH_LIBRARY})
	target_link_libraries(problem-200 ${MATH_LIBRARY})
endif()
