if(MATH_LIBRARY)
  add_executable(problem-101 problem-101.c)
  target_link_libraries(problem-101 ${MATH_LIBRARY})
endif()
add_executable(problem-102 problem-102.c)
add_executable(problem-103 problem-103.c)
if(MATH_LIBRARY)
  add_executable(problem-104 problem-104.c)
  target_link_libraries(problem-104 ${MATH_LIBRARY})
endif()
add_executable(problem-105 problem-105.c)
add_executable(problem-106 problem-106.c)
add_executable(problem-107 problem-107.c)
add_executable(problem-108 problem-108.c)
add_executable(problem-109 problem-109.c)
add_executable(problem-110 problem-110.c)
add_executable(problem-111 problem-111.c)
add_executable(problem-112 problem-112.c)
add_executable(problem-113 problem-113.c)
add_executable(problem-114 problem-114.c)
add_executable(problem-115 problem-115.c)
add_executable(problem-116 problem-116.c)
add_executable(problem-117 problem-117.c)
add_executable(problem-118 problem-118.c)
add_executable(problem-119 problem-119.c)
add_executable(problem-120 problem-120.c)
add_executable(problem-121 problem-121.c)
add_executable(problem-122 problem-122.c)
add_executable(problem-123 problem-123.c)
add_executable(problem-124 problem-124.c)
add_executable(problem-125 problem-125.c)
add_executable(problem-126 problem-126.c)
add_executable(problem-127 problem-127.c)
add_executable(problem-128 problem-128.c)
add_executable(problem-129 problem-129.c)
add_executable(problem-130 problem-130.c)
add_executable(problem-131 problem-131.c)
add_executable(problem-132 problem-132.c)
add_executable(problem-133 problem-133.c)
add_executable(problem-134 problem-134.c)
add_executable(problem-135 problem-135.c)
add_executable(problem-136 problem-136.c)
add_executable(problem-137 problem-137.c)
add_executable(problem-138 problem-138.c)
add_executable(problem-139 problem-139.c)
if(MATH_LIBRARY)
  add_executable(problem-140 problem-140.c)
  target_link_libraries(problem-140 ${MATH_LIBRARY})
endif()
if(MATH_LIBRARY)
  add_executable(problem-141 problem-141.c)
  target_link_libraries(problem-141 ${MATH_LIBRARY})
  add_executable(problem-142 problem-142.c)
  target_link_libraries(problem-142 ${MATH_LIBRARY})
  add_executable(problem-143 problem-143.c)
  target_link_libraries(problem-143 ${MATH_LIBRARY})
  add_executable(problem-144 problem-144.c)
  target_link_libraries(problem-144 ${MATH_LIBRARY})
endif()
add_executable(problem-145 problem-145.c)
add_executable(problem-146 problem-146.c)
add_executable(problem-147 problem-147.c)
add_executable(problem-148 problem-148.c)
add_executable(problem-149 problem-149.c)
add_executable(problem-150 problem-150.c)
